// File: xula2.v
// Generated by MyHDL 1.0dev
// Date: Sat Apr  9 20:21:53 2016


`timescale 1ns/10ps

module xula2 (
    led,
    clock,
    mosi,
    miso,
    sck,
    ss
);
// a simple LED blinks example.
// This is intended to be used with the Xula, Stickit motherboard
// and an LED / button pmod board.

input led;
input clock;
output mosi;
reg mosi;
input miso;
output sck;
reg sck;
output ss;
reg ss;

reg fifobus_write;
reg [23:0] cnt;
wire full;
reg reset;
reg [4:0] reset_dly_cnt;
reg toggle;
reg [7:0] fifobus_read_data;
reg fifobus_full;
wire wr;
reg fifobus_read;
reg [7:0] fifobus_write_data;
wire rd;
wire [7:0] data;
wire empty;
reg fifobus_empty;
wire [7:0] spi_inst_cso_slave_select;
reg [7:0] spi_inst_cso_rx_fifo_count;
wire spi_inst_cso_clock_polarity;
reg spi_inst_irx_empty;
reg [7:0] spi_inst_irx_write_data;
wire [4:0] spi_inst_itx_count;
reg [2:0] spi_inst_bcnt;
wire spi_inst_cso_loopback;
reg spi_inst_itx_full;
reg spi_inst_cso_rx_full;
wire [7:0] spi_inst_itx_read_data;
wire spi_inst_cso_manual_slave_select;
reg spi_inst_fifobus_read_valid;
wire spi_inst_cso_enable;
reg [2:0] spi_inst_state;
wire [7:0] spi_inst_irx_read_data;
reg spi_inst_x_ss;
reg [7:0] spi_inst_itx_write_data;
wire spi_inst_irx_read_valid;
wire spi_inst_cso_tx_write;
reg [11:0] spi_inst_clkcnt;
wire [7:0] spi_inst_cso_tx_byte;
reg spi_inst_irx_write;
reg spi_inst_cso_tx_empty;
reg spi_inst_ena;
reg spi_inst_x_miso;
wire [4:0] spi_inst_irx_count;
reg spi_inst_cso_rx_empty;
reg spi_inst_x_sck;
wire spi_inst_cso_freeze;
wire spi_inst_cso_bypass_fifo;
reg [7:0] spi_inst_rreg;
reg spi_inst_itx_empty;
reg spi_inst_cso_rx_byte_valid;
wire [7:0] spi_inst_cso_clock_divisor;
reg spi_inst_itx_write;
reg [7:0] spi_inst_cso_rx_byte;
reg spi_inst_itx_read;
reg [7:0] spi_inst_cso_tx_fifo_count;
wire spi_inst_x_mosi;
reg [7:0] spi_inst_treg;
reg spi_inst_cso_tx_full;
reg spi_inst_irx_full;
reg spi_inst_irx_read;
wire spi_inst_cso_rx_read;
wire spi_inst_cso_clock_phase;
reg [3:0] spi_inst_fifo_rx_inst_addr;
wire [4:0] spi_inst_fifo_rx_inst_ntenant;
wire spi_inst_fifo_rx_inst_fbus_clear;
reg [3:0] spi_inst_fifo_tx_inst_addr;
wire [4:0] spi_inst_fifo_tx_inst_ntenant;
wire spi_inst_fifo_tx_inst_fbus_clear;
wire spi_inst_fifo_tx_inst_fbus_read_valid;
wire cfg_inst_gens_0_keep;
wire cfg_inst_gens_0_gas_5_keep;
wire cfg_inst_gens_0_gas_4_keep;
wire cfg_inst_gens_0_gas_3_keep;
wire cfg_inst_gens_0_gas_2_keep;
wire cfg_inst_gens_0_gas_1_keep;
wire cfg_inst_gens_0_gas_0_keep;
wire inst_spi_sl_spibus_mosi;
reg [7:0] inst_spi_sl_ireg;
wire inst_spi_sl_csn;
reg inst_spi_sl_gotit;
reg inst_spi_sl_writepath_empty;
wire inst_spi_sl_sck;
reg inst_spi_sl_writepath_read;
reg inst_spi_sl_spi_start;
reg [7:0] inst_spi_sl_readpath_write_data;
wire [7:0] inst_spi_sl_icaps;
reg [7:0] inst_spi_sl_oreg;
reg [7:0] inst_spi_sl_icap;
reg [3:0] inst_spi_sl_bitcnt;
reg inst_spi_sl_spibus_miso;
reg [7:0] inst_spi_sl_ocap;
reg [3:0] inst_spi_sl_b2;
wire [3:0] inst_spi_sl_b3;
wire [7:0] inst_spi_sl_writepath_read_data;
reg inst_spi_sl_readpath_write;
wire inst_spi_sl_mp_fifo_inst_readpath_read;
wire [7:0] inst_spi_sl_mp_fifo_inst_writepath_write_data;
wire inst_spi_sl_mp_fifo_inst_readpath_read_valid;
reg inst_spi_sl_mp_fifo_inst_readpath_empty;
wire [7:0] inst_spi_sl_mp_fifo_inst_self_read_data;
wire inst_spi_sl_mp_fifo_inst_self_full;
wire inst_spi_sl_mp_fifo_inst_self_empty;
reg inst_spi_sl_mp_fifo_inst_writepath_full;
wire [7:0] inst_spi_sl_mp_fifo_inst_readpath_read_data;
wire inst_spi_sl_mp_fifo_inst_self_read;
wire [7:0] inst_spi_sl_mp_fifo_inst_self_write_data;
wire inst_spi_sl_mp_fifo_inst_writepath_write;
wire inst_spi_sl_mp_fifo_inst_self_write;
wire inst_spi_sl_mp_fifo_inst_self_read_valid;
reg [4:0] inst_spi_sl_rx_fifo_inst_nvacant;
reg inst_spi_sl_rx_fifo_inst_fbus_full;
reg [3:0] inst_spi_sl_rx_fifo_inst_addr;
reg [4:0] inst_spi_sl_rx_fifo_inst_ntenant;
wire inst_spi_sl_rx_fifo_inst_fbus_clear;
wire [4:0] inst_spi_sl_rx_fifo_inst_fbus_count;
reg [4:0] inst_spi_sl_tx_fifo_inst_nvacant;
reg [3:0] inst_spi_sl_tx_fifo_inst_addr;
reg [4:0] inst_spi_sl_tx_fifo_inst_ntenant;
wire inst_spi_sl_tx_fifo_inst_fbus_clear;
wire [4:0] inst_spi_sl_tx_fifo_inst_fbus_count;
wire inst_spi_sl_tx_fifo_inst_fbus_read_valid;

reg [7:0] spi_inst_fifo_rx_inst_mem [0:16-1];
reg [7:0] spi_inst_fifo_tx_inst_mem [0:16-1];
reg [3:0] inst_spi_sl_isync2_inst_staps [0:3-1];
reg [7:0] inst_spi_sl_isync1_inst_staps [0:3-1];
reg [7:0] inst_spi_sl_rx_fifo_inst_mem [0:16-1];
reg [7:0] inst_spi_sl_tx_fifo_inst_mem [0:16-1];

assign spi_inst_cso_manual_slave_select = 1'd0;
assign spi_inst_cso_tx_write = 1'd0;
assign spi_inst_cso_tx_byte = 8'd0;
assign spi_inst_cso_rx_read = 1'd0;
assign spi_inst_fifo_rx_inst_ntenant = 5'd0;
assign spi_inst_fifo_rx_inst_fbus_clear = 1'd0;
assign spi_inst_fifo_tx_inst_ntenant = 5'd0;
assign spi_inst_fifo_tx_inst_fbus_clear = 1'd0;
assign cfg_inst_gens_0_keep = 1'd0;
assign inst_spi_sl_spibus_mosi = 1'd1;
assign inst_spi_sl_csn = 1'd1;
assign inst_spi_sl_sck = 1'd0;
assign inst_spi_sl_mp_fifo_inst_self_read = 1'd0;
assign inst_spi_sl_mp_fifo_inst_self_write_data = 8'd0;
assign inst_spi_sl_mp_fifo_inst_self_write = 1'd0;
assign inst_spi_sl_rx_fifo_inst_fbus_clear = 1'd0;
assign inst_spi_sl_tx_fifo_inst_fbus_clear = 1'd0;



always @(posedge clock) begin: XULA2_RTL
    if (($signed({1'b0, cnt}) == (12000000 - 1))) begin
        toggle <= (!toggle);
        cnt <= 0;
    end
    else begin
        cnt <= (cnt + 1);
    end
end


always @(fifobus_full, fifobus_read_data, fifobus_empty) begin: XULA2_TB_FIFO_LOOPBACK
    if ((!fifobus_full)) begin
        fifobus_write = (!fifobus_empty);
        fifobus_read = (!fifobus_empty);
        fifobus_write_data = fifobus_read_data;
    end
end

// For the first 4 clocks the reset is forced to lo
// for clock 6 to 31 the reset is set hi
// then the reset is lo
always @(posedge clock) begin: XULA2_RESET_TST
    if ((reset_dly_cnt < 31)) begin
        reset_dly_cnt <= (reset_dly_cnt + 1);
        if ((reset_dly_cnt <= 4)) begin
            reset <= 0;
        end
        if ((reset_dly_cnt >= 5)) begin
            reset <= 1;
        end
    end
    else begin
        reset <= 0;
    end
end


always @(posedge clock) begin: XULA2_INST_SPI_SL_BEH_IO_CAPTURE
    inst_spi_sl_readpath_write <= 1'b0;
    inst_spi_sl_writepath_read <= 1'b0;
    if ((inst_spi_sl_b3 == 0)) begin
        inst_spi_sl_gotit <= 1'b0;
    end
    else if (((inst_spi_sl_b3 == 8) && (!inst_spi_sl_gotit))) begin
        inst_spi_sl_readpath_write <= 1'b1;
        inst_spi_sl_readpath_write_data <= inst_spi_sl_icaps;
        inst_spi_sl_gotit <= 1'b1;
        inst_spi_sl_ocap <= inst_spi_sl_writepath_read_data;
        if ((!inst_spi_sl_writepath_empty)) begin
            inst_spi_sl_writepath_read <= 1'b1;
        end
    end
end



assign inst_spi_sl_tx_fifo_inst_fbus_count = inst_spi_sl_tx_fifo_inst_ntenant;



assign inst_spi_sl_writepath_read_data = inst_spi_sl_tx_fifo_inst_mem[inst_spi_sl_tx_fifo_inst_addr];


always @(posedge clock) begin: XULA2_INST_SPI_SL_TX_FIFO_INST_RTL_OCCUPANCY
    if (reset == 1) begin
        inst_spi_sl_tx_fifo_inst_nvacant <= 10;
        inst_spi_sl_tx_fifo_inst_ntenant <= 00;
    end
    else begin
        if (inst_spi_sl_tx_fifo_inst_fbus_clear) begin
            inst_spi_sl_tx_fifo_inst_nvacant <= 16;
            inst_spi_sl_tx_fifo_inst_ntenant <= 0;
        end
        else if ((inst_spi_sl_writepath_read && (!inst_spi_sl_mp_fifo_inst_writepath_write))) begin
            inst_spi_sl_tx_fifo_inst_nvacant <= (inst_spi_sl_tx_fifo_inst_nvacant + 1);
            inst_spi_sl_tx_fifo_inst_ntenant <= (inst_spi_sl_tx_fifo_inst_ntenant - 1);
        end
        else if ((inst_spi_sl_mp_fifo_inst_writepath_write && (!inst_spi_sl_writepath_read))) begin
            inst_spi_sl_tx_fifo_inst_nvacant <= (inst_spi_sl_tx_fifo_inst_nvacant - 1);
            inst_spi_sl_tx_fifo_inst_ntenant <= (inst_spi_sl_tx_fifo_inst_ntenant + 1);
        end
    end
end


always @(posedge clock) begin: XULA2_INST_SPI_SL_TX_FIFO_INST_RTL_SRL_IN
    integer jj;
    if (inst_spi_sl_mp_fifo_inst_writepath_write) begin
        inst_spi_sl_tx_fifo_inst_mem[0] <= inst_spi_sl_mp_fifo_inst_writepath_write_data;
        for (jj=1; jj<16; jj=jj+1) begin
            inst_spi_sl_tx_fifo_inst_mem[jj] <= inst_spi_sl_tx_fifo_inst_mem[(jj - 1)];
        end
    end
end


always @(posedge clock) begin: XULA2_INST_SPI_SL_TX_FIFO_INST_RTL_FIFO
    if (reset == 1) begin
        inst_spi_sl_mp_fifo_inst_writepath_full <= 0;
        inst_spi_sl_writepath_empty <= 1;
        inst_spi_sl_tx_fifo_inst_addr <= 0;
    end
    else begin
        if (inst_spi_sl_tx_fifo_inst_fbus_clear) begin
            inst_spi_sl_tx_fifo_inst_addr <= 0;
            inst_spi_sl_writepath_empty <= 1'b1;
            inst_spi_sl_mp_fifo_inst_writepath_full <= 1'b0;
        end
        else if ((inst_spi_sl_writepath_read && (!inst_spi_sl_mp_fifo_inst_writepath_write))) begin
            inst_spi_sl_mp_fifo_inst_writepath_full <= 1'b0;
            if ((inst_spi_sl_tx_fifo_inst_addr == 0)) begin
                inst_spi_sl_writepath_empty <= 1'b1;
            end
            else begin
                inst_spi_sl_tx_fifo_inst_addr <= (inst_spi_sl_tx_fifo_inst_addr - 1);
            end
        end
        else if ((inst_spi_sl_mp_fifo_inst_writepath_write && (!inst_spi_sl_writepath_read))) begin
            inst_spi_sl_writepath_empty <= 1'b0;
            if ((!inst_spi_sl_writepath_empty)) begin
                inst_spi_sl_tx_fifo_inst_addr <= (inst_spi_sl_tx_fifo_inst_addr + 1);
            end
            if (($signed({1'b0, inst_spi_sl_tx_fifo_inst_addr}) == (16 - 2))) begin
                inst_spi_sl_mp_fifo_inst_writepath_full <= 1'b1;
            end
        end
    end
end



assign inst_spi_sl_tx_fifo_inst_fbus_read_valid = (inst_spi_sl_writepath_read && (!inst_spi_sl_writepath_empty));


always @(posedge inst_spi_sl_sck, posedge inst_spi_sl_csn) begin: XULA2_INST_SPI_SL_SCK_CAPTURE_SEND
    if (inst_spi_sl_csn) begin
        inst_spi_sl_b2 <= 0;
        inst_spi_sl_bitcnt <= 0;
    end
    else begin
        if (((inst_spi_sl_bitcnt == 0) || inst_spi_sl_spi_start)) begin
            inst_spi_sl_spibus_miso <= inst_spi_sl_ocap[7];
            inst_spi_sl_oreg <= ((inst_spi_sl_ocap << 1) & 255);
        end
        else begin
            inst_spi_sl_spibus_miso <= inst_spi_sl_oreg[7];
            inst_spi_sl_oreg <= ((inst_spi_sl_oreg << 1) & 255);
        end
        inst_spi_sl_ireg <= {inst_spi_sl_ireg[7-1:0], inst_spi_sl_spibus_mosi};
        inst_spi_sl_bitcnt <= (inst_spi_sl_bitcnt + 1);
        if (($signed({1'b0, inst_spi_sl_bitcnt}) == (8 - 1))) begin
            inst_spi_sl_bitcnt <= 0;
            inst_spi_sl_b2 <= 8;
            inst_spi_sl_icap <= {inst_spi_sl_ireg[7-1:0], inst_spi_sl_spibus_mosi};
        end
        else begin
            inst_spi_sl_b2 <= 0;
        end
    end
end



assign inst_spi_sl_rx_fifo_inst_fbus_count = inst_spi_sl_rx_fifo_inst_ntenant;



assign inst_spi_sl_mp_fifo_inst_readpath_read_data = inst_spi_sl_rx_fifo_inst_mem[inst_spi_sl_rx_fifo_inst_addr];


always @(posedge clock) begin: XULA2_INST_SPI_SL_RX_FIFO_INST_RTL_OCCUPANCY
    if (reset == 1) begin
        inst_spi_sl_rx_fifo_inst_nvacant <= 10;
        inst_spi_sl_rx_fifo_inst_ntenant <= 00;
    end
    else begin
        if (inst_spi_sl_rx_fifo_inst_fbus_clear) begin
            inst_spi_sl_rx_fifo_inst_nvacant <= 16;
            inst_spi_sl_rx_fifo_inst_ntenant <= 0;
        end
        else if ((inst_spi_sl_mp_fifo_inst_readpath_read && (!inst_spi_sl_readpath_write))) begin
            inst_spi_sl_rx_fifo_inst_nvacant <= (inst_spi_sl_rx_fifo_inst_nvacant + 1);
            inst_spi_sl_rx_fifo_inst_ntenant <= (inst_spi_sl_rx_fifo_inst_ntenant - 1);
        end
        else if ((inst_spi_sl_readpath_write && (!inst_spi_sl_mp_fifo_inst_readpath_read))) begin
            inst_spi_sl_rx_fifo_inst_nvacant <= (inst_spi_sl_rx_fifo_inst_nvacant - 1);
            inst_spi_sl_rx_fifo_inst_ntenant <= (inst_spi_sl_rx_fifo_inst_ntenant + 1);
        end
    end
end


always @(posedge clock) begin: XULA2_INST_SPI_SL_RX_FIFO_INST_RTL_SRL_IN
    integer jj;
    if (inst_spi_sl_readpath_write) begin
        inst_spi_sl_rx_fifo_inst_mem[0] <= inst_spi_sl_readpath_write_data;
        for (jj=1; jj<16; jj=jj+1) begin
            inst_spi_sl_rx_fifo_inst_mem[jj] <= inst_spi_sl_rx_fifo_inst_mem[(jj - 1)];
        end
    end
end


always @(posedge clock) begin: XULA2_INST_SPI_SL_RX_FIFO_INST_RTL_FIFO
    if (reset == 1) begin
        inst_spi_sl_rx_fifo_inst_fbus_full <= 0;
        inst_spi_sl_mp_fifo_inst_readpath_empty <= 1;
        inst_spi_sl_rx_fifo_inst_addr <= 0;
    end
    else begin
        if (inst_spi_sl_rx_fifo_inst_fbus_clear) begin
            inst_spi_sl_rx_fifo_inst_addr <= 0;
            inst_spi_sl_mp_fifo_inst_readpath_empty <= 1'b1;
            inst_spi_sl_rx_fifo_inst_fbus_full <= 1'b0;
        end
        else if ((inst_spi_sl_mp_fifo_inst_readpath_read && (!inst_spi_sl_readpath_write))) begin
            inst_spi_sl_rx_fifo_inst_fbus_full <= 1'b0;
            if ((inst_spi_sl_rx_fifo_inst_addr == 0)) begin
                inst_spi_sl_mp_fifo_inst_readpath_empty <= 1'b1;
            end
            else begin
                inst_spi_sl_rx_fifo_inst_addr <= (inst_spi_sl_rx_fifo_inst_addr - 1);
            end
        end
        else if ((inst_spi_sl_readpath_write && (!inst_spi_sl_mp_fifo_inst_readpath_read))) begin
            inst_spi_sl_mp_fifo_inst_readpath_empty <= 1'b0;
            if ((!inst_spi_sl_mp_fifo_inst_readpath_empty)) begin
                inst_spi_sl_rx_fifo_inst_addr <= (inst_spi_sl_rx_fifo_inst_addr + 1);
            end
            if (($signed({1'b0, inst_spi_sl_rx_fifo_inst_addr}) == (16 - 2))) begin
                inst_spi_sl_rx_fifo_inst_fbus_full <= 1'b1;
            end
        end
    end
end



assign inst_spi_sl_mp_fifo_inst_readpath_read_valid = (inst_spi_sl_mp_fifo_inst_readpath_read && (!inst_spi_sl_mp_fifo_inst_readpath_empty));



assign inst_spi_sl_mp_fifo_inst_writepath_write = inst_spi_sl_mp_fifo_inst_self_write;
assign inst_spi_sl_mp_fifo_inst_writepath_write_data = inst_spi_sl_mp_fifo_inst_self_write_data;
assign inst_spi_sl_mp_fifo_inst_self_full = inst_spi_sl_mp_fifo_inst_writepath_full;
assign inst_spi_sl_mp_fifo_inst_readpath_read = inst_spi_sl_mp_fifo_inst_self_read;
assign inst_spi_sl_mp_fifo_inst_self_read_data = inst_spi_sl_mp_fifo_inst_readpath_read_data;
assign inst_spi_sl_mp_fifo_inst_self_read_valid = inst_spi_sl_mp_fifo_inst_readpath_read_valid;
assign inst_spi_sl_mp_fifo_inst_self_empty = inst_spi_sl_mp_fifo_inst_readpath_empty;



assign inst_spi_sl_icaps = inst_spi_sl_isync1_inst_staps[(3 - 1)];


always @(posedge clock) begin: XULA2_INST_SPI_SL_ISYNC1_INST_BEH_SYNC_STAGES
    integer ii;
    inst_spi_sl_isync1_inst_staps[0] <= inst_spi_sl_icap;
    for (ii=1; ii<3; ii=ii+1) begin
        inst_spi_sl_isync1_inst_staps[ii] <= inst_spi_sl_isync1_inst_staps[(ii - 1)];
    end
end


always @(posedge inst_spi_sl_sck, negedge inst_spi_sl_csn) begin: XULA2_INST_SPI_SL_CSN_FALLS
    if (inst_spi_sl_sck) begin
        inst_spi_sl_spi_start <= 1'b0;
    end
    else if ((!inst_spi_sl_csn)) begin
        inst_spi_sl_spi_start <= 1'b1;
    end
end



assign inst_spi_sl_b3 = inst_spi_sl_isync2_inst_staps[(3 - 1)];


always @(posedge clock) begin: XULA2_INST_SPI_SL_ISYNC2_INST_BEH_SYNC_STAGES
    integer ii;
    inst_spi_sl_isync2_inst_staps[0] <= inst_spi_sl_b2;
    for (ii=1; ii<3; ii=ii+1) begin
        inst_spi_sl_isync2_inst_staps[ii] <= inst_spi_sl_isync2_inst_staps[(ii - 1)];
    end
end

// In the static configuration case only one value makes sense
// for certain configuration signals, those are set here

assign spi_inst_cso_enable = cfg_inst_gens_0_keep ? 1'b1 : 1'b1;
assign spi_inst_cso_freeze = 1'b0;



assign spi_inst_cso_clock_polarity = cfg_inst_gens_0_gas_0_keep ? 0 : 0;



assign spi_inst_cso_loopback = cfg_inst_gens_0_gas_1_keep ? 0 : 0;



assign spi_inst_cso_slave_select = cfg_inst_gens_0_gas_2_keep ? 0 : 0;



assign spi_inst_cso_clock_phase = cfg_inst_gens_0_gas_3_keep ? 0 : 0;



assign spi_inst_cso_clock_divisor = cfg_inst_gens_0_gas_4_keep ? 0 : 0;



assign spi_inst_cso_bypass_fifo = cfg_inst_gens_0_gas_5_keep ? 0 : 0;


always @(posedge clock) begin: XULA2_SPI_INST_GENS_0
    if ((spi_inst_cso_enable && (spi_inst_clkcnt != 0) && (spi_inst_state != 3'b000))) begin
        spi_inst_clkcnt <= (spi_inst_clkcnt - 1);
    end
    else begin
        case (spi_inst_cso_clock_divisor)
            0: spi_inst_clkcnt <= 0;
            1: spi_inst_clkcnt <= 1;
            2: spi_inst_clkcnt <= 3;
            3: spi_inst_clkcnt <= 7;
            4: spi_inst_clkcnt <= 15;
            5: spi_inst_clkcnt <= 31;
            6: spi_inst_clkcnt <= 63;
            7: spi_inst_clkcnt <= 127;
            8: spi_inst_clkcnt <= 255;
            9: spi_inst_clkcnt <= 511;
            10: spi_inst_clkcnt <= 1023;
            11: spi_inst_clkcnt <= 2047;
            default: spi_inst_clkcnt <= 4095;
        endcase
    end
end


always @(spi_inst_x_mosi, miso, spi_inst_x_sck, spi_inst_cso_loopback) begin: XULA2_SPI_INST_GENS_1
    sck = spi_inst_x_sck;
    if (spi_inst_cso_loopback) begin
        spi_inst_x_miso = spi_inst_x_mosi;
    end
    else begin
        spi_inst_x_miso = miso;
    end
end



assign spi_inst_itx_count = spi_inst_fifo_tx_inst_ntenant;



assign spi_inst_itx_read_data = spi_inst_fifo_tx_inst_mem[spi_inst_fifo_tx_inst_addr];


always @(posedge clock) begin: XULA2_SPI_INST_FIFO_TX_INST_RTL_SRL_IN
    integer jj;
    if (spi_inst_itx_write) begin
        spi_inst_fifo_tx_inst_mem[0] <= spi_inst_itx_write_data;
        for (jj=1; jj<16; jj=jj+1) begin
            spi_inst_fifo_tx_inst_mem[jj] <= spi_inst_fifo_tx_inst_mem[(jj - 1)];
        end
    end
end


always @(posedge clock) begin: XULA2_SPI_INST_FIFO_TX_INST_RTL_FIFO
    if (reset == 1) begin
        spi_inst_itx_full <= 0;
        spi_inst_itx_empty <= 1;
        spi_inst_fifo_tx_inst_addr <= 0;
    end
    else begin
        if (spi_inst_fifo_tx_inst_fbus_clear) begin
            spi_inst_fifo_tx_inst_addr <= 0;
            spi_inst_itx_empty <= 1'b1;
            spi_inst_itx_full <= 1'b0;
        end
        else if ((spi_inst_itx_read && (!spi_inst_itx_write))) begin
            spi_inst_itx_full <= 1'b0;
            if ((spi_inst_fifo_tx_inst_addr == 0)) begin
                spi_inst_itx_empty <= 1'b1;
            end
            else begin
                spi_inst_fifo_tx_inst_addr <= (spi_inst_fifo_tx_inst_addr - 1);
            end
        end
        else if ((spi_inst_itx_write && (!spi_inst_itx_read))) begin
            spi_inst_itx_empty <= 1'b0;
            if ((!spi_inst_itx_empty)) begin
                spi_inst_fifo_tx_inst_addr <= (spi_inst_fifo_tx_inst_addr + 1);
            end
            if (($signed({1'b0, spi_inst_fifo_tx_inst_addr}) == (16 - 2))) begin
                spi_inst_itx_full <= 1'b1;
            end
        end
    end
end



assign spi_inst_fifo_tx_inst_fbus_read_valid = (spi_inst_itx_read && (!spi_inst_itx_empty));


always @(spi_inst_x_mosi, spi_inst_cso_loopback) begin: XULA2_SPI_INST_RTL_GATE_MOSI
    if (spi_inst_cso_loopback) begin
        mosi = 1'b0;
    end
    else begin
        mosi = spi_inst_x_mosi;
    end
end



assign spi_inst_x_mosi = spi_inst_treg[7];

// Designed to the following timing diagram
// 
// SCK   CPOL=0 ______/---\___/---\___/---\___/---\___/---\___/---\___/---\___/---\___/---\ 
//       CPOL=1 ------\___/---\___/---\___/---\___/---\___/---\___/---\___/---\___/---\___/ 
// SS           ---\_______________________________________________________________________ 
// CPHA=0 MOSI  ...|.0....|.1.....|.2.....|.3.....|.4.....|.5.....|.6.....|.7.....|.0.....| 
//        MISO  ...|.0....|.1.....|.2.....|.3.....|.4.....|.5.....|.6.....|.7.....|.0.....| 
// CPHA=1 MOSI  ...|....0.....|.1.....|.2.....|.3.....|.4.....|.5.....|.6.....|.7.....|.0...
//        MISO  ......|.0.....|.1.....|.2.....|.3.....|.4.....|.5.....|.6.....|.7.....|.0...
always @(posedge clock) begin: XULA2_SPI_INST_RTL_STATE_AND_MORE
    if (reset == 1) begin
        spi_inst_itx_read <= 0;
        spi_inst_x_sck <= 0;
        spi_inst_treg <= 00;
        spi_inst_state <= 3'b000;
        spi_inst_bcnt <= 0;
        spi_inst_x_ss <= 0;
        spi_inst_irx_write <= 0;
        spi_inst_rreg <= 00;
    end
    else begin
        if ((!spi_inst_cso_enable)) begin
            spi_inst_state <= 3'b000;
            spi_inst_bcnt <= 0;
            spi_inst_treg <= 0;
            spi_inst_itx_read <= 1'b0;
            spi_inst_irx_write <= 1'b0;
            spi_inst_x_sck <= 1'b0;
            spi_inst_x_ss <= 1'b0;
        end
        else begin
            if ((!spi_inst_cso_freeze)) begin
                case (spi_inst_state)
                    3'b000: begin
                        spi_inst_bcnt <= 7;
                        spi_inst_treg <= spi_inst_itx_read_data;
                        spi_inst_x_sck <= spi_inst_cso_clock_polarity;
                        spi_inst_irx_write <= 1'b0;
                        if (((!spi_inst_itx_empty) && (!spi_inst_irx_full))) begin
                            spi_inst_itx_read <= 1'b1;
                            spi_inst_x_ss <= 1'b0;
                            if (spi_inst_cso_clock_phase) begin
                                spi_inst_state <= 3'b001;
                            end
                            else begin
                                spi_inst_state <= 3'b010;
                            end
                        end
                        else begin
                            spi_inst_itx_read <= 1'b0;
                            spi_inst_x_ss <= 1'b1;
                        end
                    end
                    3'b001: begin
                        spi_inst_itx_read <= 1'b0;
                        spi_inst_irx_write <= 1'b0;
                        if (spi_inst_ena) begin
                            spi_inst_x_sck <= (!spi_inst_x_sck);
                            spi_inst_state <= 3'b010;
                        end
                    end
                    3'b010: begin
                        spi_inst_itx_read <= 1'b0;
                        spi_inst_irx_write <= 1'b0;
                        if (spi_inst_ena) begin
                            spi_inst_x_sck <= (!spi_inst_x_sck);
                            spi_inst_rreg <= {spi_inst_rreg[7-1:0], spi_inst_x_miso};
                            if ((spi_inst_cso_clock_phase && (spi_inst_bcnt == 0))) begin
                                spi_inst_irx_write <= 1'b1;
                                if ((spi_inst_itx_empty || spi_inst_irx_full)) begin
                                    spi_inst_state <= 3'b101;
                                end
                                else begin
                                    spi_inst_state <= 3'b011;
                                end
                            end
                            else begin
                                spi_inst_state <= 3'b011;
                            end
                        end
                    end
                    3'b011: begin
                        spi_inst_itx_read <= 1'b0;
                        spi_inst_irx_write <= 1'b0;
                        if (spi_inst_ena) begin
                            spi_inst_x_sck <= (!spi_inst_x_sck);
                            if ((spi_inst_bcnt == 0)) begin
                                if ((!spi_inst_cso_clock_phase)) begin
                                    spi_inst_irx_write <= 1'b1;
                                end
                                if ((spi_inst_itx_empty || spi_inst_irx_full)) begin
                                    spi_inst_state <= 3'b101;
                                end
                                else begin
                                    spi_inst_bcnt <= 7;
                                    spi_inst_state <= 3'b010;
                                    spi_inst_itx_read <= 1'b1;
                                    spi_inst_treg <= spi_inst_itx_read_data;
                                end
                            end
                            else begin
                                spi_inst_treg <= {spi_inst_treg[7-1:0], 1'h0};
                                spi_inst_bcnt <= (spi_inst_bcnt - 1);
                                spi_inst_state <= 3'b010;
                            end
                        end
                    end
                    3'b101: begin
                        spi_inst_itx_read <= 1'b0;
                        spi_inst_irx_write <= 1'b0;
                        if (spi_inst_ena) begin
                            spi_inst_state <= 3'b000;
                        end
                    end
                    default: begin
                        spi_inst_state <= 3'b000;
                        if (1'b0 !== 1) begin
                            $display("*** AssertionError ***");
                        end
                    end
                endcase
            end
        end
    end
end


always @(spi_inst_irx_count, spi_inst_clkcnt, spi_inst_itx_count) begin: XULA2_SPI_INST_RTL_ASSIGN
    spi_inst_cso_tx_fifo_count = spi_inst_itx_count;
    spi_inst_cso_rx_fifo_count = spi_inst_irx_count;
    if ((spi_inst_clkcnt > 0)) begin
        spi_inst_ena = 1'b0;
    end
    else begin
        spi_inst_ena = 1'b1;
    end
end


always @(spi_inst_cso_slave_select, spi_inst_x_ss, spi_inst_cso_manual_slave_select) begin: XULA2_SPI_INST_RTL_SLAVE_SELECT
    if (spi_inst_cso_manual_slave_select) begin
        ss = (~spi_inst_cso_slave_select);
    end
    else if (spi_inst_x_ss) begin
        ss = 255;
    end
    else begin
        ss = (~spi_inst_cso_slave_select);
    end
end

// The `itx` and `irx` FIFO interfaces are driven by different
// logic depending on the configuration.  This modules accesses
// the `itx` read side and drives the `irx` write side.  The
// `itx` write side is driven by the `cso` or the `fifobus` port.
// The `irx` read side is accessed by the `cso` or the `fifobus`
// port.
always @(fifobus_write, spi_inst_rreg, spi_inst_irx_empty, spi_inst_cso_rx_read, spi_inst_cso_bypass_fifo, spi_inst_itx_full, spi_inst_irx_read_data, spi_inst_irx_full, spi_inst_itx_empty, fifobus_read, spi_inst_irx_read_valid, spi_inst_cso_tx_write, fifobus_write_data, spi_inst_cso_tx_byte) begin: XULA2_SPI_INST_RTL_FIFO_SEL
    if (spi_inst_cso_bypass_fifo) begin
        spi_inst_cso_tx_empty = spi_inst_itx_empty;
        spi_inst_cso_tx_full = spi_inst_itx_full;
        spi_inst_itx_write_data = spi_inst_cso_tx_byte;
        spi_inst_cso_rx_empty = spi_inst_irx_empty;
        spi_inst_cso_rx_full = spi_inst_irx_full;
        spi_inst_cso_rx_byte = spi_inst_irx_read_data;
        spi_inst_cso_rx_byte_valid = spi_inst_irx_read_valid;
        spi_inst_itx_write = spi_inst_cso_tx_write;
        spi_inst_irx_read = spi_inst_cso_rx_read;
    end
    else begin
        fifobus_full = spi_inst_itx_full;
        spi_inst_itx_write_data = fifobus_write_data;
        spi_inst_itx_write = fifobus_write;
        fifobus_empty = spi_inst_irx_empty;
        fifobus_read_data = spi_inst_irx_read_data;
        spi_inst_fifobus_read_valid = spi_inst_irx_read_valid;
        spi_inst_irx_read = fifobus_read;
    end
    spi_inst_irx_write_data = spi_inst_rreg;
end



assign spi_inst_irx_count = spi_inst_fifo_rx_inst_ntenant;



assign spi_inst_irx_read_data = spi_inst_fifo_rx_inst_mem[spi_inst_fifo_rx_inst_addr];


always @(posedge clock) begin: XULA2_SPI_INST_FIFO_RX_INST_RTL_SRL_IN
    integer jj;
    if (spi_inst_irx_write) begin
        spi_inst_fifo_rx_inst_mem[0] <= spi_inst_irx_write_data;
        for (jj=1; jj<16; jj=jj+1) begin
            spi_inst_fifo_rx_inst_mem[jj] <= spi_inst_fifo_rx_inst_mem[(jj - 1)];
        end
    end
end


always @(posedge clock) begin: XULA2_SPI_INST_FIFO_RX_INST_RTL_FIFO
    if (reset == 1) begin
        spi_inst_irx_full <= 0;
        spi_inst_irx_empty <= 1;
        spi_inst_fifo_rx_inst_addr <= 0;
    end
    else begin
        if (spi_inst_fifo_rx_inst_fbus_clear) begin
            spi_inst_fifo_rx_inst_addr <= 0;
            spi_inst_irx_empty <= 1'b1;
            spi_inst_irx_full <= 1'b0;
        end
        else if ((spi_inst_irx_read && (!spi_inst_irx_write))) begin
            spi_inst_irx_full <= 1'b0;
            if ((spi_inst_fifo_rx_inst_addr == 0)) begin
                spi_inst_irx_empty <= 1'b1;
            end
            else begin
                spi_inst_fifo_rx_inst_addr <= (spi_inst_fifo_rx_inst_addr - 1);
            end
        end
        else if ((spi_inst_irx_write && (!spi_inst_irx_read))) begin
            spi_inst_irx_empty <= 1'b0;
            if ((!spi_inst_irx_empty)) begin
                spi_inst_fifo_rx_inst_addr <= (spi_inst_fifo_rx_inst_addr + 1);
            end
            if (($signed({1'b0, spi_inst_fifo_rx_inst_addr}) == (16 - 2))) begin
                spi_inst_irx_full <= 1'b1;
            end
        end
    end
end



assign spi_inst_irx_read_valid = (spi_inst_irx_read && (!spi_inst_irx_empty));



assign data = fifobus_read_data;
assign rd = fifobus_read;
assign wr = fifobus_write;
assign full = fifobus_full;
assign empty = fifobus_empty;

endmodule
