// File: const_assign.v
// Generated by MyHDL 0.9.dev0
// Date: Tue May 26 06:58:51 2015


`timescale 1ns/10ps

module const_assign (
    aBit,
    aByte
);


output aBit;
wire aBit;
output [7:0] aByte;
wire [7:0] aByte;

wire b;


assign b = 1;




assign aBit = b;
assign aByte = 85;

endmodule
