// File: xula2.v
// Generated by MyHDL 1.0dev
// Date: Fri Apr  8 09:39:48 2016


`timescale 1ns/10ps

module xula2 (
    mosi,
    miso
);


input mosi;
output miso;
wire miso;







assign miso = mosi;

endmodule
