// File: lift_step.v
// Generated by MyHDL 1.0dev
// Date: Sat Oct 24 12:25:07 2015


`timescale 1ns/10ps

module lift_step (
    flags_i,
    update_i,
    left_i,
    sam_i,
    right_i,
    res_o,
    update_o,
    clk_i
);


input [2:0] flags_i;
input update_i;
input [8:0] left_i;
input [8:0] sam_i;
input [8:0] right_i;
output signed [9:0] res_o;
reg signed [9:0] res_o;
output update_o;
reg update_o;
input clk_i;






always @(posedge clk_i) begin: LIFT_STEP_RTL
    if ((update_i == 1)) begin
        update_o <= 0;
        case (flags_i)
            'h7: begin
                res_o <= ($signed(sam_i) - ($signed($signed(left_i) >>> 1) + $signed($signed(right_i) >>> 1)));
            end
            'h5: begin
                res_o <= ($signed(sam_i) + ($signed($signed(left_i) >>> 1) + $signed($signed(right_i) >>> 1)));
            end
            'h6: begin
                res_o <= ($signed(sam_i) + $signed((($signed(left_i) + $signed(right_i)) + 2) >>> 2));
            end
            'h4: begin
                res_o <= ($signed(sam_i) - $signed((($signed(left_i) + $signed(right_i)) + 2) >>> 2));
            end
        endcase
    end
    else begin
        update_o <= 1;
    end
end

endmodule
