-- File: signed2twoscomplement.vhd
-- Generated by MyHDL 1.0dev
-- Date: Sat Oct 24 10:38:06 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_10.all;

entity signed2twoscomplement is
    port (
        clk: in std_logic;
        res_o: in signed (9 downto 0);
        z: out unsigned(8 downto 0)
    );
end entity signed2twoscomplement;


architecture MyHDL of signed2twoscomplement is






begin





SIGNED2TWOSCOMPLEMENT_UNSIGNED_LOGIC: process (clk) is
begin
    if rising_edge(clk) then
        z <= resize(unsigned(res_o), 9);
    end if;
end process SIGNED2TWOSCOMPLEMENT_UNSIGNED_LOGIC;

end architecture MyHDL;
