-intstyle "ise" -incremental -lib "secureip" -o "C:/Xilinx/14.7/ISE_DS/SdramSPInst/SdramSPIinstTB_isim_beh.exe" -prj "C:/Xilinx/14.7/ISE_DS/SdramSPInst/SdramSPIinstTB_beh.prj" "work.SdramSPIinstTB" 
