// File: jpeg.v
// Generated by MyHDL 0.9dev
// Date: Fri Sep  5 13:53:45 2014


`timescale 1ns/10ps

module jpeg (
    clk_fast,
    left_r,
    right_r,
    sam_r,
    res_s,
    even_odd_s,
    fwd_inv_s
);


input clk_fast;
input signed [15:0] left_r;
input signed [15:0] right_r;
input signed [15:0] sam_r;
output signed [15:0] res_s;
reg signed [15:0] res_s;
input even_odd_s;
input fwd_inv_s;






always @(posedge clk_fast) begin: JPEG_HDL
    if (even_odd_s) begin
        if (fwd_inv_s) begin
            res_s <= (sam_r - ($signed(left_r >>> 1) + $signed(right_r >>> 1)));
        end
        else begin
            res_s <= (sam_r + ($signed(left_r >>> 1) + $signed(right_r >>> 1)));
        end
    end
    else begin
        if (fwd_inv_s) begin
            res_s <= (sam_r + $signed(((left_r + right_r) + 2) >>> 2));
        end
        else begin
            res_s <= (sam_r - $signed(((left_r + right_r) + 2) >>> 2));
        end
    end
end

endmodule
