// File: del_test.v
// Generated by MyHDL 0.9dev
// Date: Sun Sep 28 07:37:08 2014


`timescale 1ns/10ps

module del_test (
    clk_fast,
    left_s,
    signed_res_s
);


input clk_fast;
input signed [15:0] left_s;
output signed [15:0] signed_res_s;
reg signed [15:0] signed_res_s;






always @(posedge clk_fast) begin: DEL_TEST_HDL
    signed_res_s <= (left_s + 1);
end

endmodule
