-- File: del_test.vhd
-- Generated by MyHDL 0.9dev
-- Date: Sun Sep 28 07:37:08 2014


library IEEE,XESS;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use XESS.ClkgenPckg.all;     -- For the clock generator module.
use XESS.SdramCntlPckg.all;  -- For the SDRAM controller module.
use XESS.HostIoPckg.all;     -- For the FPGA<=>PC transfer link module.

use XESS.DelayPckg.all;     -- For the FPGA<=>PC transfer link module.

use work.pck_myhdl_09.all;

entity del_test is
    port (
        clk_fast: in std_logic;
        left_s: in signed (15 downto 0);
        signed_res_s: out signed (15 downto 0)
    );
end entity del_test;


architecture MyHDL of del_test is






begin




DEL_TEST_HDL: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        signed_res_s <= (left_s + 1);
    end if;
end process DEL_TEST_HDL;

end architecture MyHDL;
