// File: del_test.v
// Generated by MyHDL 0.9dev
// Date: Sun Sep 28 05:46:49 2014


`timescale 1ns/10ps

module del_test (
    clk_fast,
    left_s,
    delay_s,
    res_s
);


input clk_fast;
input signed [15:0] left_s;
input signed [15:0] delay_s;
output signed [15:0] res_s;
reg signed [15:0] res_s;






always @(posedge clk_fast) begin: DEL_TEST_HDL
    res_s <= (left_s + 1);
end

endmodule
