// File: jpeg_process.v
// Generated by MyHDL 0.9dev
// Date: Thu Oct 23 15:32:58 2014


`timescale 1ns/10ps

module jpeg_process (
    clk_fast,
    sig_in,
    noupdate_s,
    res_s
);


input clk_fast;
input [51:0] sig_in;
output noupdate_s;
reg noupdate_s;
output signed [15:0] res_s;
reg signed [15:0] res_s;






always @(posedge clk_fast) begin: JPEG_PROCESS_JPEG
    if (sig_in[50]) begin
        noupdate_s <= 0;
        if (sig_in[48]) begin
            if (sig_in[49]) begin
                res_s <= (sig_in[32-1:16] - ((sig_in[16-1:0] >>> 1) + (sig_in[48-1:32] >>> 1)));
            end
            else begin
                res_s <= (sig_in[32-1:16] + ((sig_in[16-1:0] >>> 1) + (sig_in[48-1:32] >>> 1)));
            end
        end
        else begin
            if (sig_in[49]) begin
                res_s <= (sig_in[32-1:16] + (((sig_in[16-1:0] + sig_in[48-1:32]) + 2) >>> 2));
            end
            else begin
                res_s <= (sig_in[32-1:16] - (((sig_in[16-1:0] + sig_in[48-1:32]) + 2) >>> 2));
            end
        end
    end
    else begin
        noupdate_s <= 1;
    end
end

endmodule
