// File: latch.v
// Generated by MyHDL 0.9dev
// Date: Sat Oct 18 07:50:33 2014


`timescale 1ns/10ps

module latch (
    q_o,
    d_i,
    g
);


output [15:0] q_o;
reg [15:0] q_o;
input [15:0] d_i;
input g;






always @(d_i, g) begin: LATCH_LOGIC
    if ((g == 1)) begin
        q_o = d_i;
    end
end

endmodule
