-- File: latch.vhd
-- Generated by MyHDL 0.9dev
-- Date: Sat Oct 18 07:50:33 2014


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity latch is
    port (
        q_o: out unsigned(15 downto 0);
        d_i: in unsigned(15 downto 0);
        g: in std_logic
    );
end entity latch;


architecture MyHDL of latch is






begin




LATCH_LOGIC: process (d_i, g) is
begin
    if (g = '1') then
        q_o <= d_i;
    end if;
end process LATCH_LOGIC;

end architecture MyHDL;
