// File: mux.v
// Generated by MyHDL 0.9dev
// Date: Thu Oct 16 16:36:13 2014


`timescale 1ns/10ps

module mux (
    z_o,
    left_i,
    right_i,
    sel
);


output [15:0] z_o;
reg [15:0] z_o;
input [15:0] left_i;
input [15:0] right_i;
input sel;






always @(right_i, sel, left_i) begin: MUX_MUXLOGIC
    if ((sel == 1)) begin
        z_o = left_i;
    end
    else begin
        z_o = right_i;
    end
end

endmodule
