-- File: mux.vhd
-- Generated by MyHDL 0.9dev
-- Date: Thu Oct 16 16:36:13 2014


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity mux is
    port (
        z_o: out unsigned(15 downto 0);
        left_i: in unsigned(15 downto 0);
        right_i: in unsigned(15 downto 0);
        sel: in std_logic
    );
end entity mux;


architecture MyHDL of mux is






begin




MUX_MUXLOGIC: process (right_i, sel, left_i) is
begin
    if (sel = '1') then
        z_o <= left_i;
    else
        z_o <= right_i;
    end if;
end process MUX_MUXLOGIC;

end architecture MyHDL;
