-- File: ram.vhd
-- Generated by MyHDL 0.9dev
-- Date: Mon Oct  6 15:53:14 2014


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity ram is
    port (
        dout: out unsigned(15 downto 0);
        din: in unsigned(15 downto 0);
        addr: in unsigned(6 downto 0);
        we: in std_logic;
        clk_fast: in std_logic
    );
end entity ram;
-- Ram model 

architecture MyHDL of ram is





type t_array_mem is array(0 to 256-1) of unsigned(7 downto 0);
signal mem: t_array_mem;

begin




RAM_WRITE: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(we) then
            mem(to_integer(addr)) <= resize(din, 8);
        end if;
    end if;
end process RAM_WRITE;



dout <= resize(mem(to_integer(addr)), 16);

end architecture MyHDL;
