// File: ram.v
// Generated by MyHDL 0.9dev
// Date: Tue Oct  7 12:14:50 2014


`timescale 1ns/10ps

module ram (
    dout,
    din,
    addr,
    we,
    clk_fast
);
// Ram model 

output [15:0] dout;
wire [15:0] dout;
input [15:0] din;
input [8:0] addr;
input we;
input clk_fast;


reg [15:0] mem [0:256-1];




always @(posedge clk_fast) begin: RAM_WRITE
    if (we) begin
        mem[addr] <= din;
    end
end



assign dout = mem[addr];

endmodule
