// File: ram2sig.v
// Generated by MyHDL 0.9dev
// Date: Sat Oct 25 10:19:14 2014


`timescale 1ns/10ps

module ram2sig (
    jp_lf,
    jp_sa,
    jp_rh,
    jp_flgs,
    rdy,
    sig_out
);
// Combines 3 16 bit plus 4 flags into single value 

input [15:0] jp_lf;
input [15:0] jp_sa;
input [15:0] jp_rh;
input [3:0] jp_flgs;
input rdy;
output [51:0] sig_out;
reg [51:0] sig_out;






always @(jp_sa, jp_flgs, jp_lf, rdy, jp_rh) begin: RAM2SIG_LOGIC
    if (rdy) begin
        sig_out = {jp_flgs, jp_rh, jp_sa, jp_lf};
    end
    else begin
        sig_out = 0;
    end
end

endmodule
