-- File: rom_rd.vhd
-- Generated by MyHDL 0.9dev
-- Date: Mon Oct 27 11:42:42 2014


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity rom_rd is
    port (
        clk_fast: in std_logic;
        offset: in unsigned(11 downto 0);
        dout_rom: in unsigned(15 downto 0);
        addr_rom: inout unsigned(11 downto 0);
        jp_lf: out unsigned(15 downto 0);
        jp_sa: out unsigned(15 downto 0);
        jp_rh: out unsigned(15 downto 0);
        jp_flgs: in unsigned(3 downto 0);
        reset_n: in std_logic
    );
end entity rom_rd;


architecture MyHDL of rom_rd is






begin




ROM_RD_TEST_PROCESS: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(reset_n) then
            jp_lf <= to_unsigned(0, 16);
            jp_sa <= to_unsigned(0, 16);
            jp_rh <= to_unsigned(0, 16);
            if (jp_flgs(0) = '1') then
                addr_rom <= (1 + offset);
            else
                addr_rom <= (0 + offset);
            end if;
        else
            if bool(jp_flgs(0)) then
                if (addr_rom = (1 + offset)) then
                    jp_lf <= dout_rom;
                    addr_rom <= (addr_rom + 1);
                else
                    if (addr_rom = (2 + offset)) then
                        jp_sa <= dout_rom;
                        addr_rom <= (addr_rom + 1);
                    else
                        if (addr_rom = (3 + offset)) then
                            jp_rh <= dout_rom;
                        end if;
                    end if;
                end if;
            elsif (addr_rom = (0 + offset)) then
                jp_lf <= dout_rom;
                addr_rom <= (addr_rom + 1);
            else
                if (addr_rom = (1 + offset)) then
                    jp_sa <= dout_rom;
                    addr_rom <= (addr_rom + 1);
                else
                    if (addr_rom = (2 + offset)) then
                        jp_rh <= dout_rom;
                    end if;
                end if;
            end if;
        end if;
    end if;
end process ROM_RD_TEST_PROCESS;

end architecture MyHDL;
