// File: save_to_ram.v
// Generated by MyHDL 0.9dev
// Date: Thu Oct  9 09:40:35 2014


`timescale 1ns/10ps

module save_to_ram (
    clk_fast,
    dout_res_o,
    res_i,
    we_s_o,
    reset_sav_i,
    addr_res_o,
    incRes_i,
    odd_i
);


input clk_fast;
output [15:0] dout_res_o;
reg [15:0] dout_res_o;
input signed [15:0] res_i;
output we_s_o;
reg we_s_o;
input reset_sav_i;
output [8:0] addr_res_o;
reg [8:0] addr_res_o;
input incRes_i;
input odd_i;






always @(posedge clk_fast) begin: SAVE_TO_RAM_XX
    if ((reset_sav_i == 1)) begin
        we_s_o <= 0;
        if ((odd_i == 1)) begin
            addr_res_o <= 1;
        end
        else begin
            addr_res_o <= 2;
        end
    end
    else if ((incRes_i == 1)) begin
        we_s_o <= 0;
        addr_res_o <= (addr_res_o + 2);
    end
    else begin
        we_s_o <= 1;
        dout_res_o <= res_i;
    end
end

endmodule
