// File: FsmUpdate_p.v
// Generated by MyHDL 0.9dev
// Date: Thu Oct  2 13:42:47 2014


`timescale 1ns/10ps

module FsmUpdate_p (
    clk_s,
    addr_r,
    addr_x,
    sam_addr_r,
    sam_addr_x,
    updated_r,
    updated_x,
    sigDelayed_r,
    sigDelayed_x,
    addrjpeg_r,
    addrjpeg_x,
    dataToRam_r,
    dataToRam_x
);


input clk_s;
output [13:0] addr_r;
reg [13:0] addr_r;
input [13:0] addr_x;
output [13:0] sam_addr_r;
reg [13:0] sam_addr_r;
input [13:0] sam_addr_x;
output updated_r;
reg updated_r;
input updated_x;
output sigDelayed_r;
reg sigDelayed_r;
input sigDelayed_x;
output [13:0] addrjpeg_r;
reg [13:0] addrjpeg_r;
input [13:0] addrjpeg_x;
output [15:0] dataToRam_r;
reg [15:0] dataToRam_r;
input [15:0] dataToRam_x;






always @(posedge clk_s) begin: FSMUPDATE_P_HDL
    addr_r <= addr_x;
    sam_addr_r <= sam_addr_x;
    addrjpeg_r <= addrjpeg_x;
    updated_r <= updated_x;
    sigDelayed_r <= sigDelayed_x;
    dataToRam_r <= dataToRam_x;
end

endmodule
