-- File: FsmUpdate_p.vhd
-- Generated by MyHDL 0.9dev
-- Date: Thu Oct  2 13:42:47 2014


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity FsmUpdate_p is
    port (
        clk_s: in std_logic;
        addr_r: out unsigned(13 downto 0);
        addr_x: in unsigned(13 downto 0);
        sam_addr_r: out unsigned(13 downto 0);
        sam_addr_x: in unsigned(13 downto 0);
        updated_r: out std_logic;
        updated_x: in std_logic;
        sigDelayed_r: out std_logic;
        sigDelayed_x: in std_logic;
        addrjpeg_r: out unsigned(13 downto 0);
        addrjpeg_x: in unsigned(13 downto 0);
        dataToRam_r: out unsigned(15 downto 0);
        dataToRam_x: in unsigned(15 downto 0)
    );
end entity FsmUpdate_p;


architecture MyHDL of FsmUpdate_p is






begin




FSMUPDATE_P_HDL: process (clk_s) is
begin
    if rising_edge(clk_s) then
        addr_r <= addr_x;
        sam_addr_r <= sam_addr_x;
        addrjpeg_r <= addrjpeg_x;
        updated_r <= updated_x;
        sigDelayed_r <= sigDelayed_x;
        dataToRam_r <= dataToRam_x;
    end if;
end process FSMUPDATE_P_HDL;

end architecture MyHDL;
