-- File: combine.vhd
-- Generated by MyHDL 0.9dev
-- Date: Wed Mar 18 10:41:54 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity combine is
    port (
        left_com_x: out unsigned(143 downto 0);
        sam_com_x: out unsigned(143 downto 0);
        right_com_x: out unsigned(143 downto 0);
        lft_s_i: in unsigned(143 downto 0);
        sa_s_i: in unsigned(143 downto 0);
        rht_s_i: in unsigned(143 downto 0);
        combine_rdy_s: in std_logic;
        nocombine_s: out std_logic
    );
end entity combine;


architecture MyHDL of combine is





type t_array_rht_s is array(0 to 16-1) of unsigned(8 downto 0);
signal rht_s: t_array_rht_s;
type t_array_sa_s is array(0 to 16-1) of unsigned(8 downto 0);
signal sa_s: t_array_sa_s;
type t_array_lft_s is array(0 to 16-1) of unsigned(8 downto 0);
signal lft_s: t_array_lft_s;

begin


rht_s(0) <= rht_s_i(9-1 downto 0);
rht_s(1) <= rht_s_i(18-1 downto 9);
rht_s(2) <= rht_s_i(27-1 downto 18);
rht_s(3) <= rht_s_i(36-1 downto 27);
rht_s(4) <= rht_s_i(45-1 downto 36);
rht_s(5) <= rht_s_i(54-1 downto 45);
rht_s(6) <= rht_s_i(63-1 downto 54);
rht_s(7) <= rht_s_i(72-1 downto 63);
rht_s(8) <= rht_s_i(81-1 downto 72);
rht_s(9) <= rht_s_i(90-1 downto 81);
rht_s(10) <= rht_s_i(99-1 downto 90);
rht_s(11) <= rht_s_i(108-1 downto 99);
rht_s(12) <= rht_s_i(117-1 downto 108);
rht_s(13) <= rht_s_i(126-1 downto 117);
rht_s(14) <= rht_s_i(135-1 downto 126);
rht_s(15) <= rht_s_i(144-1 downto 135);
sa_s(0) <= sa_s_i(9-1 downto 0);
sa_s(1) <= sa_s_i(18-1 downto 9);
sa_s(2) <= sa_s_i(27-1 downto 18);
sa_s(3) <= sa_s_i(36-1 downto 27);
sa_s(4) <= sa_s_i(45-1 downto 36);
sa_s(5) <= sa_s_i(54-1 downto 45);
sa_s(6) <= sa_s_i(63-1 downto 54);
sa_s(7) <= sa_s_i(72-1 downto 63);
sa_s(8) <= sa_s_i(81-1 downto 72);
sa_s(9) <= sa_s_i(90-1 downto 81);
sa_s(10) <= sa_s_i(99-1 downto 90);
sa_s(11) <= sa_s_i(108-1 downto 99);
sa_s(12) <= sa_s_i(117-1 downto 108);
sa_s(13) <= sa_s_i(126-1 downto 117);
sa_s(14) <= sa_s_i(135-1 downto 126);
sa_s(15) <= sa_s_i(144-1 downto 135);
lft_s(0) <= lft_s_i(9-1 downto 0);
lft_s(1) <= lft_s_i(18-1 downto 9);
lft_s(2) <= lft_s_i(27-1 downto 18);
lft_s(3) <= lft_s_i(36-1 downto 27);
lft_s(4) <= lft_s_i(45-1 downto 36);
lft_s(5) <= lft_s_i(54-1 downto 45);
lft_s(6) <= lft_s_i(63-1 downto 54);
lft_s(7) <= lft_s_i(72-1 downto 63);
lft_s(8) <= lft_s_i(81-1 downto 72);
lft_s(9) <= lft_s_i(90-1 downto 81);
lft_s(10) <= lft_s_i(99-1 downto 90);
lft_s(11) <= lft_s_i(108-1 downto 99);
lft_s(12) <= lft_s_i(117-1 downto 108);
lft_s(13) <= lft_s_i(126-1 downto 117);
lft_s(14) <= lft_s_i(135-1 downto 126);
lft_s(15) <= lft_s_i(144-1 downto 135);


COMBINE_COMBINE_LOGIC: process (rht_s, sa_s, lft_s, combine_rdy_s) is
begin
    if (combine_rdy_s = '1') then
        left_com_x <= unsigned'(lft_s(15) & lft_s(14) & lft_s(13) & lft_s(12) & lft_s(11) & lft_s(10) & lft_s(9) & lft_s(8) & lft_s(7) & lft_s(6) & lft_s(5) & lft_s(4) & lft_s(3) & lft_s(2) & lft_s(1) & lft_s(0));
        sam_com_x <= unsigned'(sa_s(15) & sa_s(14) & sa_s(13) & sa_s(12) & sa_s(11) & sa_s(10) & sa_s(9) & sa_s(8) & sa_s(7) & sa_s(6) & sa_s(5) & sa_s(4) & sa_s(3) & sa_s(2) & sa_s(1) & sa_s(0));
        right_com_x <= unsigned'(rht_s(15) & rht_s(14) & rht_s(13) & rht_s(12) & rht_s(11) & rht_s(10) & rht_s(9) & rht_s(8) & rht_s(7) & rht_s(6) & rht_s(5) & rht_s(4) & rht_s(3) & rht_s(2) & rht_s(1) & rht_s(0));
        nocombine_s <= '0';
    else
        left_com_x <= to_unsigned(0, 144);
        sam_com_x <= to_unsigned(0, 144);
        right_com_x <= to_unsigned(0, 144);
        nocombine_s <= '1';
    end if;
end process COMBINE_COMBINE_LOGIC;

end architecture MyHDL;
