// File: m_flatten.v
// Generated by MyHDL 0.9dev
// Date: Wed Mar 18 10:54:07 2015


`timescale 1ns/10ps

module m_flatten (
    flat
);


output [143:0] flat;
wire [143:0] flat;

wire [143:0] _flat;
wire [8:0] mcol;


assign mcol = 0;

assign _flat[144-1:135] = None;
assign _flat[135-1:126] = None;
assign _flat[126-1:117] = None;
assign _flat[117-1:108] = None;
assign _flat[108-1:99] = None;
assign _flat[99-1:90] = None;
assign _flat[90-1:81] = None;
assign _flat[81-1:72] = None;
assign _flat[72-1:63] = None;
assign _flat[63-1:54] = None;
assign _flat[54-1:45] = None;
assign _flat[45-1:36] = None;
assign _flat[36-1:27] = None;
assign _flat[27-1:18] = None;
assign _flat[18-1:9] = None;
assign _flat[9-1:0] = mcol[9-1:0];



assign flat = _flat;

endmodule
