// File: m_flatten.v
// Generated by MyHDL 0.9dev
// Date: Sat Mar 14 20:35:37 2015


`timescale 1ns/10ps

module m_flatten (
    flat
);


output [255:0] flat;
wire [255:0] flat;

wire [255:0] _flat;
wire [15:0] mcol;


assign mcol = 0;

assign _flat[256-1:240] = None;
assign _flat[240-1:224] = None;
assign _flat[224-1:208] = None;
assign _flat[208-1:192] = None;
assign _flat[192-1:176] = None;
assign _flat[176-1:160] = None;
assign _flat[160-1:144] = None;
assign _flat[144-1:128] = None;
assign _flat[128-1:112] = None;
assign _flat[112-1:96] = None;
assign _flat[96-1:80] = None;
assign _flat[80-1:64] = None;
assign _flat[64-1:48] = None;
assign _flat[48-1:32] = None;
assign _flat[32-1:16] = None;
assign _flat[16-1:0] = mcol[16-1:0];



assign flat = _flat;

endmodule
