-- File: m_flatten.vhd
-- Generated by MyHDL 0.9dev
-- Date: Tue Mar 17 12:59:18 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity m_flatten is
    port (
        flat: out unsigned(127 downto 0)
    );
end entity m_flatten;


architecture MyHDL of m_flatten is





signal _flat: unsigned(127 downto 0);
signal mcol: unsigned(7 downto 0);

begin

mcol <= to_unsigned(0, 8);

_flat(128-1 downto 120) <= None;
_flat(120-1 downto 112) <= None;
_flat(112-1 downto 104) <= None;
_flat(104-1 downto 96) <= None;
_flat(96-1 downto 88) <= None;
_flat(88-1 downto 80) <= None;
_flat(80-1 downto 72) <= None;
_flat(72-1 downto 64) <= None;
_flat(64-1 downto 56) <= None;
_flat(56-1 downto 48) <= None;
_flat(48-1 downto 40) <= None;
_flat(40-1 downto 32) <= None;
_flat(32-1 downto 24) <= None;
_flat(24-1 downto 16) <= None;
_flat(16-1 downto 8) <= None;
_flat(8-1 downto 0) <= mcol(8-1 downto 0);



flat <= _flat;

end architecture MyHDL;
