-- File: m_flatten.vhd
-- Generated by MyHDL 0.9dev
-- Date: Thu Mar 26 04:59:23 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity m_flatten is
    port (
        flat: out unsigned(143 downto 0)
    );
end entity m_flatten;


architecture MyHDL of m_flatten is





signal mcol: unsigned(8 downto 0);
signal flat_i: unsigned(143 downto 0);

begin

mcol <= to_unsigned(0, 9);

flat_i(144-1 downto 135) <= None;
flat_i(135-1 downto 126) <= None;
flat_i(126-1 downto 117) <= None;
flat_i(117-1 downto 108) <= None;
flat_i(108-1 downto 99) <= None;
flat_i(99-1 downto 90) <= None;
flat_i(90-1 downto 81) <= None;
flat_i(81-1 downto 72) <= None;
flat_i(72-1 downto 63) <= None;
flat_i(63-1 downto 54) <= None;
flat_i(54-1 downto 45) <= None;
flat_i(45-1 downto 36) <= None;
flat_i(36-1 downto 27) <= None;
flat_i(27-1 downto 18) <= None;
flat_i(18-1 downto 9) <= None;
flat_i(9-1 downto 0) <= mcol(9-1 downto 0);



flat <= flat_i;

end architecture MyHDL;
