-- File: m_flatten.vhd
-- Generated by MyHDL 0.9dev
-- Date: Wed Mar 18 10:54:07 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity m_flatten is
    port (
        flat: out unsigned(143 downto 0)
    );
end entity m_flatten;


architecture MyHDL of m_flatten is





signal _flat: unsigned(143 downto 0);
signal mcol: unsigned(8 downto 0);

begin

mcol <= to_unsigned(0, 9);

_flat(144-1 downto 135) <= None;
_flat(135-1 downto 126) <= None;
_flat(126-1 downto 117) <= None;
_flat(117-1 downto 108) <= None;
_flat(108-1 downto 99) <= None;
_flat(99-1 downto 90) <= None;
_flat(90-1 downto 81) <= None;
_flat(81-1 downto 72) <= None;
_flat(72-1 downto 63) <= None;
_flat(63-1 downto 54) <= None;
_flat(54-1 downto 45) <= None;
_flat(45-1 downto 36) <= None;
_flat(36-1 downto 27) <= None;
_flat(27-1 downto 18) <= None;
_flat(18-1 downto 9) <= None;
_flat(9-1 downto 0) <= mcol(9-1 downto 0);



flat <= _flat;

end architecture MyHDL;
