// File: matrix_wrap.v
// Generated by MyHDL 0.9dev
// Date: Wed Mar 25 10:40:01 2015


`timescale 1ns/10ps

module matrix_wrap (
    flat,
    z,
    x,
    mrow,
    mcol
);


output [143:0] flat;
wire [143:0] flat;
input [8:0] z;
input signed [9:0] x;
input [3:0] mrow;
input [3:0] mcol;

wire [143:0] mat__flat;
wire [8:0] mat_mcol;


assign mat_mcol = 0;

assign mat__flat[144-1:135] = None;
assign mat__flat[135-1:126] = None;
assign mat__flat[126-1:117] = None;
assign mat__flat[117-1:108] = None;
assign mat__flat[108-1:99] = None;
assign mat__flat[99-1:90] = None;
assign mat__flat[90-1:81] = None;
assign mat__flat[81-1:72] = None;
assign mat__flat[72-1:63] = None;
assign mat__flat[63-1:54] = None;
assign mat__flat[54-1:45] = None;
assign mat__flat[45-1:36] = None;
assign mat__flat[36-1:27] = None;
assign mat__flat[27-1:18] = None;
assign mat__flat[18-1:9] = None;
assign mat__flat[9-1:0] = mat_mcol[9-1:0];



assign flat = mat__flat;

endmodule
