-- File: multi_jpeg.vhd
-- Generated by MyHDL 0.9dev
-- Date: Mon Jan 26 16:57:04 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity multi_jpeg is
    port (
        clk_fast: in std_logic;
        sig0_in_x: in unsigned(30 downto 0);
        noupdate0_s: out std_logic;
        res0_s: out signed (10 downto 0);
        sig1_in_x: in unsigned(30 downto 0);
        noupdate1_s: out std_logic;
        res1_s: out signed (10 downto 0);
        sig2_in_x: in unsigned(30 downto 0);
        noupdate2_s: out std_logic;
        res2_s: out signed (10 downto 0);
        sig3_in_x: in unsigned(30 downto 0);
        noupdate3_s: out std_logic;
        res3_s: out signed (10 downto 0);
        sig4_in_x: in unsigned(30 downto 0);
        noupdate4_s: out std_logic;
        res4_s: out signed (10 downto 0);
        sig5_in_x: in unsigned(30 downto 0);
        noupdate5_s: out std_logic;
        res5_s: out signed (10 downto 0);
        sig6_in_x: in unsigned(30 downto 0);
        noupdate6_s: out std_logic;
        res6_s: out signed (10 downto 0);
        sig7_in_x: in unsigned(30 downto 0);
        noupdate7_s: out std_logic;
        res7_s: out signed (10 downto 0)
    );
end entity multi_jpeg;


architecture MyHDL of multi_jpeg is






begin




MULTI_JPEG_INSTANCE_0_JPEG: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(sig0_in_x(29)) then
            noupdate0_s <= '0';
            if bool(sig0_in_x(27)) then
                if bool(sig0_in_x(28)) then
                    res0_s <= signed(resize(sig0_in_x(18-1 downto 9), 11) - (shift_right(resize(sig0_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig0_in_x(27-1 downto 18), 11), 1)));
                else
                    res0_s <= signed(resize(sig0_in_x(18-1 downto 9), 11) + (shift_right(resize(sig0_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig0_in_x(27-1 downto 18), 11), 1)));
                end if;
            else
                if bool(sig0_in_x(28)) then
                    res0_s <= signed(resize(sig0_in_x(18-1 downto 9), 11) + shift_right(((resize(sig0_in_x(9-1 downto 0), 11) + sig0_in_x(27-1 downto 18)) + 2), 2));
                else
                    res0_s <= signed(resize(sig0_in_x(18-1 downto 9), 11) - shift_right(((resize(sig0_in_x(9-1 downto 0), 11) + sig0_in_x(27-1 downto 18)) + 2), 2));
                end if;
            end if;
        else
            noupdate0_s <= '1';
        end if;
    end if;
end process MULTI_JPEG_INSTANCE_0_JPEG;


MULTI_JPEG_INSTANCE_1_JPEG: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(sig1_in_x(29)) then
            noupdate1_s <= '0';
            if bool(sig1_in_x(27)) then
                if bool(sig1_in_x(28)) then
                    res1_s <= signed(resize(sig1_in_x(18-1 downto 9), 11) - (shift_right(resize(sig1_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig1_in_x(27-1 downto 18), 11), 1)));
                else
                    res1_s <= signed(resize(sig1_in_x(18-1 downto 9), 11) + (shift_right(resize(sig1_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig1_in_x(27-1 downto 18), 11), 1)));
                end if;
            else
                if bool(sig1_in_x(28)) then
                    res1_s <= signed(resize(sig1_in_x(18-1 downto 9), 11) + shift_right(((resize(sig1_in_x(9-1 downto 0), 11) + sig1_in_x(27-1 downto 18)) + 2), 2));
                else
                    res1_s <= signed(resize(sig1_in_x(18-1 downto 9), 11) - shift_right(((resize(sig1_in_x(9-1 downto 0), 11) + sig1_in_x(27-1 downto 18)) + 2), 2));
                end if;
            end if;
        else
            noupdate1_s <= '1';
        end if;
    end if;
end process MULTI_JPEG_INSTANCE_1_JPEG;


MULTI_JPEG_INSTANCE_2_JPEG: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(sig2_in_x(29)) then
            noupdate2_s <= '0';
            if bool(sig2_in_x(27)) then
                if bool(sig2_in_x(28)) then
                    res2_s <= signed(resize(sig2_in_x(18-1 downto 9), 11) - (shift_right(resize(sig2_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig2_in_x(27-1 downto 18), 11), 1)));
                else
                    res2_s <= signed(resize(sig2_in_x(18-1 downto 9), 11) + (shift_right(resize(sig2_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig2_in_x(27-1 downto 18), 11), 1)));
                end if;
            else
                if bool(sig2_in_x(28)) then
                    res2_s <= signed(resize(sig2_in_x(18-1 downto 9), 11) + shift_right(((resize(sig2_in_x(9-1 downto 0), 11) + sig2_in_x(27-1 downto 18)) + 2), 2));
                else
                    res2_s <= signed(resize(sig2_in_x(18-1 downto 9), 11) - shift_right(((resize(sig2_in_x(9-1 downto 0), 11) + sig2_in_x(27-1 downto 18)) + 2), 2));
                end if;
            end if;
        else
            noupdate2_s <= '1';
        end if;
    end if;
end process MULTI_JPEG_INSTANCE_2_JPEG;


MULTI_JPEG_INSTANCE_3_JPEG: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(sig3_in_x(29)) then
            noupdate3_s <= '0';
            if bool(sig3_in_x(27)) then
                if bool(sig3_in_x(28)) then
                    res3_s <= signed(resize(sig3_in_x(18-1 downto 9), 11) - (shift_right(resize(sig3_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig3_in_x(27-1 downto 18), 11), 1)));
                else
                    res3_s <= signed(resize(sig3_in_x(18-1 downto 9), 11) + (shift_right(resize(sig3_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig3_in_x(27-1 downto 18), 11), 1)));
                end if;
            else
                if bool(sig3_in_x(28)) then
                    res3_s <= signed(resize(sig3_in_x(18-1 downto 9), 11) + shift_right(((resize(sig3_in_x(9-1 downto 0), 11) + sig3_in_x(27-1 downto 18)) + 2), 2));
                else
                    res3_s <= signed(resize(sig3_in_x(18-1 downto 9), 11) - shift_right(((resize(sig3_in_x(9-1 downto 0), 11) + sig3_in_x(27-1 downto 18)) + 2), 2));
                end if;
            end if;
        else
            noupdate3_s <= '1';
        end if;
    end if;
end process MULTI_JPEG_INSTANCE_3_JPEG;


MULTI_JPEG_INSTANCE_4_JPEG: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(sig4_in_x(29)) then
            noupdate4_s <= '0';
            if bool(sig4_in_x(27)) then
                if bool(sig4_in_x(28)) then
                    res4_s <= signed(resize(sig4_in_x(18-1 downto 9), 11) - (shift_right(resize(sig4_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig4_in_x(27-1 downto 18), 11), 1)));
                else
                    res4_s <= signed(resize(sig4_in_x(18-1 downto 9), 11) + (shift_right(resize(sig4_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig4_in_x(27-1 downto 18), 11), 1)));
                end if;
            else
                if bool(sig4_in_x(28)) then
                    res4_s <= signed(resize(sig4_in_x(18-1 downto 9), 11) + shift_right(((resize(sig4_in_x(9-1 downto 0), 11) + sig4_in_x(27-1 downto 18)) + 2), 2));
                else
                    res4_s <= signed(resize(sig4_in_x(18-1 downto 9), 11) - shift_right(((resize(sig4_in_x(9-1 downto 0), 11) + sig4_in_x(27-1 downto 18)) + 2), 2));
                end if;
            end if;
        else
            noupdate4_s <= '1';
        end if;
    end if;
end process MULTI_JPEG_INSTANCE_4_JPEG;


MULTI_JPEG_INSTANCE_5_JPEG: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(sig5_in_x(29)) then
            noupdate5_s <= '0';
            if bool(sig5_in_x(27)) then
                if bool(sig5_in_x(28)) then
                    res5_s <= signed(resize(sig5_in_x(18-1 downto 9), 11) - (shift_right(resize(sig5_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig5_in_x(27-1 downto 18), 11), 1)));
                else
                    res5_s <= signed(resize(sig5_in_x(18-1 downto 9), 11) + (shift_right(resize(sig5_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig5_in_x(27-1 downto 18), 11), 1)));
                end if;
            else
                if bool(sig5_in_x(28)) then
                    res5_s <= signed(resize(sig5_in_x(18-1 downto 9), 11) + shift_right(((resize(sig5_in_x(9-1 downto 0), 11) + sig5_in_x(27-1 downto 18)) + 2), 2));
                else
                    res5_s <= signed(resize(sig5_in_x(18-1 downto 9), 11) - shift_right(((resize(sig5_in_x(9-1 downto 0), 11) + sig5_in_x(27-1 downto 18)) + 2), 2));
                end if;
            end if;
        else
            noupdate5_s <= '1';
        end if;
    end if;
end process MULTI_JPEG_INSTANCE_5_JPEG;


MULTI_JPEG_INSTANCE_6_JPEG: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(sig6_in_x(29)) then
            noupdate6_s <= '0';
            if bool(sig6_in_x(27)) then
                if bool(sig6_in_x(28)) then
                    res6_s <= signed(resize(sig6_in_x(18-1 downto 9), 11) - (shift_right(resize(sig6_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig6_in_x(27-1 downto 18), 11), 1)));
                else
                    res6_s <= signed(resize(sig6_in_x(18-1 downto 9), 11) + (shift_right(resize(sig6_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig6_in_x(27-1 downto 18), 11), 1)));
                end if;
            else
                if bool(sig6_in_x(28)) then
                    res6_s <= signed(resize(sig6_in_x(18-1 downto 9), 11) + shift_right(((resize(sig6_in_x(9-1 downto 0), 11) + sig6_in_x(27-1 downto 18)) + 2), 2));
                else
                    res6_s <= signed(resize(sig6_in_x(18-1 downto 9), 11) - shift_right(((resize(sig6_in_x(9-1 downto 0), 11) + sig6_in_x(27-1 downto 18)) + 2), 2));
                end if;
            end if;
        else
            noupdate6_s <= '1';
        end if;
    end if;
end process MULTI_JPEG_INSTANCE_6_JPEG;


MULTI_JPEG_INSTANCE_7_JPEG: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(sig7_in_x(29)) then
            noupdate7_s <= '0';
            if bool(sig7_in_x(27)) then
                if bool(sig7_in_x(28)) then
                    res7_s <= signed(resize(sig7_in_x(18-1 downto 9), 11) - (shift_right(resize(sig7_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig7_in_x(27-1 downto 18), 11), 1)));
                else
                    res7_s <= signed(resize(sig7_in_x(18-1 downto 9), 11) + (shift_right(resize(sig7_in_x(9-1 downto 0), 11), 1) + shift_right(resize(sig7_in_x(27-1 downto 18), 11), 1)));
                end if;
            else
                if bool(sig7_in_x(28)) then
                    res7_s <= signed(resize(sig7_in_x(18-1 downto 9), 11) + shift_right(((resize(sig7_in_x(9-1 downto 0), 11) + sig7_in_x(27-1 downto 18)) + 2), 2));
                else
                    res7_s <= signed(resize(sig7_in_x(18-1 downto 9), 11) - shift_right(((resize(sig7_in_x(9-1 downto 0), 11) + sig7_in_x(27-1 downto 18)) + 2), 2));
                end if;
            end if;
        else
            noupdate7_s <= '1';
        end if;
    end if;
end process MULTI_JPEG_INSTANCE_7_JPEG;

end architecture MyHDL;
