-- File: ram.vhd
-- Generated by MyHDL 0.9dev
-- Date: Tue Mar 24 10:04:43 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity ram is
    port (
        dout: out unsigned(143 downto 0);
        din: in unsigned(143 downto 0);
        addr: in unsigned(9 downto 0);
        we: in std_logic;
        clk_fast: in std_logic
    );
end entity ram;
-- Ram model 

architecture MyHDL of ram is





type t_array_mem is array(0 to 512-1) of unsigned(143 downto 0);
signal mem: t_array_mem;

begin




RAM_WRITE: process (clk_fast) is
begin
    if rising_edge(clk_fast) then
        if bool(we) then
            mem(to_integer(addr)) <= din;
        end if;
    end if;
end process RAM_WRITE;



dout <= mem(to_integer(addr));

end architecture MyHDL;
