-- File: ram_res.vhd
-- Generated by MyHDL 0.9dev
-- Date: Tue Mar 31 11:22:59 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity ram_res is
    port (
        dout_res: out unsigned(8 downto 0);
        din_res: in unsigned(8 downto 0);
        addr_res: in unsigned(9 downto 0);
        we_res: in std_logic;
        clk_fast: in std_logic
    );
end entity ram_res;
-- Ram model 

architecture MyHDL of ram_res is





type t_array_mem is array(0 to 512-1) of unsigned(8 downto 0);
signal mem: t_array_mem;

begin




RAM_RES_WRITE: process (clk_fast) is
begin
    if falling_edge(clk_fast) then
        if bool(we_res) then
            mem(to_integer(addr_res)) <= din_res;
        end if;
    end if;
end process RAM_RES_WRITE;



dout_res <= mem(to_integer(addr_res));

end architecture MyHDL;
