// File: ram_res.v
// Generated by MyHDL 0.9dev
// Date: Thu Mar 26 15:41:57 2015


`timescale 1ns/10ps

module ram_res (
    dout_res,
    din_res,
    addr_res,
    we_res,
    clk_fast
);
// Ram model 

output [8:0] dout_res;
wire [8:0] dout_res;
input [8:0] din_res;
input [9:0] addr_res;
input we_res;
input clk_fast;


reg [8:0] mem [0:512-1];




always @(posedge clk_fast) begin: RAM_RES_WRITE
    if (we_res) begin
        mem[addr_res] <= din_res;
    end
end



assign dout_res = mem[addr_res];

endmodule
