// File: signed2twoscomplement.v
// Generated by MyHDL 0.9dev
// Date: Thu Mar 26 15:22:13 2015


`timescale 1ns/10ps

module signed2twoscomplement (
    bits_in_sig,
    vv
);
// return 

input signed [9:0] bits_in_sig;
output [8:0] vv;
wire [8:0] vv;







assign vv = bits_in_sig;

endmodule
