-- File: tosigned.vhd
-- Generated by MyHDL 0.9dev
-- Date: Wed Mar  4 14:23:13 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity tosigned is
    port (
        bits_in: in signed (9 downto 0);
        v: out unsigned(9 downto 0)
    );
end entity tosigned;
-- return a signed representation of an 'unsigned' value 

architecture MyHDL of tosigned is


constant w: integer := 10;




begin




TOSIGNED_TOSIGNED_LOGIC: process (bits_in) is
begin
    if bool((shift_right(bits_in, (w - 1)) and to_signed(1, 10))) then
        v <= unsigned((-((not bits_in) + 1)));
    else
        v <= unsigned(bits_in);
    end if;
end process TOSIGNED_TOSIGNED_LOGIC;

end architecture MyHDL;
