// File: tosigned.v
// Generated by MyHDL 0.9dev
// Date: Thu Mar  5 10:50:05 2015


`timescale 1ns/10ps

module tosigned (
    bits_in2unsigned,
    vv
);
// return a signed representation of an 'unsigned' value 

input [9:0] bits_in2unsigned;
output signed [9:0] vv;
reg signed [9:0] vv;






always @(bits_in2unsigned) begin: TOSIGNED_TOSIGNED_LOGIC
    if (($signed($signed({1'b0, bits_in2unsigned}) >>> (9 - 1)) & 1)) begin
        vv = ((~bits_in2unsigned) + 1);
    end
    else begin
        vv = bits_in2unsigned;
    end
end

endmodule
