-- File: tosigned.vhd
-- Generated by MyHDL 0.9dev
-- Date: Thu Mar  5 10:50:05 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity tosigned is
    port (
        bits_in2unsigned: in unsigned(9 downto 0);
        vv: out signed (9 downto 0)
    );
end entity tosigned;
-- return a signed representation of an 'unsigned' value 

architecture MyHDL of tosigned is


constant w: integer := 9;




begin




TOSIGNED_TOSIGNED_LOGIC: process (bits_in2unsigned) is
begin
    if bool((shift_right(bits_in2unsigned, (w - 1)) and to_unsigned(1, 10))) then
        vv <= signed((not bits_in2unsigned) + 1);
    else
        vv <= signed(bits_in2unsigned);
    end if;
end process TOSIGNED_TOSIGNED_LOGIC;

end architecture MyHDL;
