// File: add_mul.v
// Generated by MyHDL 0.9dev
// Date: Fri Jun 20 13:37:28 2014


`timescale 1ns/10ps

module add_mul (
    d3,
    a2,
    clk,
    x1,
    x2,
    x3,
    x4,
    x5,
    odd_even
);


output signed [35:0] d3;
reg signed [35:0] d3;
output signed [35:0] a2;
reg signed [35:0] a2;
input clk;
input signed [10:0] x1;
input signed [10:0] x2;
input signed [10:0] x3;
input signed [10:0] x4;
input signed [10:0] x5;
input odd_even;

wire [35:0] ca3;
wire [35:0] ca2;
wire [35:0] ca1;
wire [35:0] ca4;


assign ca3 = 115724;
assign ca2 = -6945;
assign ca1 = -207898;
assign ca4 = 58131;



always @(posedge clk) begin: ADD_MUL_RTL
    integer t;
    integer t1;
    if ((odd_even == 1)) begin
        t = ((x2 + x3) * ca1);
        t1 = ((x4 + x5) * ca2);
        d3 <= t;
        a2 <= t1;
    end
    else begin
        t = ((x2 + x3) * ca3);
        t1 = ((x4 + x5) * ca4);
        d3 <= t;
        a2 <= t1;
    end
end

endmodule
