-- File: fixbv_mul.vhd
-- Generated by MyHDL 0.9.dev0
-- Date: Mon May  4 13:19:56 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity fixbv_mul is
    port (
        clk: in std_logic;
        do_prod: in std_logic;
        x_sig: in unsigned(31 downto 0);
        y_sig: in unsigned(31 downto 0);
        prod_sig: out unsigned(63 downto 0)
    );
end entity fixbv_mul;


architecture MyHDL of fixbv_mul is






begin




FIXBV_MUL_ADD_RTL: process (clk) is
begin
    if rising_edge(clk) then
        if (do_prod = '1') then
            prod_sig <= (x_sig * y_sig);
        else
            prod_sig <= to_unsigned(0, 64);
        end if;
    end if;
end process FIXBV_MUL_ADD_RTL;

end architecture MyHDL;
