// File: fixbv_mul.v
// Generated by MyHDL 0.9.dev0
// Date: Tue May  5 16:25:40 2015


`timescale 1ns/10ps

module fixbv_mul (
    clk,
    do_mul,
    x_sig,
    y_sig,
    prod_sig,
    done_mul
);


input clk;
input do_mul;
input signed [30:0] x_sig;
input signed [30:0] y_sig;
output [61:0] prod_sig;
reg [61:0] prod_sig;
output done_mul;
reg done_mul;






always @(posedge clk) begin: FIXBV_MUL_ADD_RTL
    if ((do_mul == 1)) begin
        done_mul <= 0;
        prod_sig <= (x_sig * y_sig);
    end
    else begin
        done_mul <= 1;
        prod_sig <= 0;
    end
end

endmodule
