-- File: fixbv_sub.vhd
-- Generated by MyHDL 0.9.dev0
-- Date: Tue May  5 16:25:40 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity fixbv_sub is
    port (
        clk: in std_logic;
        do_sub: in std_logic;
        x_sig: in signed (30 downto 0);
        y_sig: in signed (30 downto 0);
        sub_sig: out signed (31 downto 0);
        done_sub: out std_logic
    );
end entity fixbv_sub;


architecture MyHDL of fixbv_sub is






begin




FIXBV_SUB_SUB_RTL: process (clk) is
begin
    if rising_edge(clk) then
        if (do_sub = '1') then
            done_sub <= '0';
            sub_sig <= (resize(x_sig, 32) - y_sig);
        else
            done_sub <= '1';
            sub_sig <= to_signed(0, 32);
        end if;
    end if;
end process FIXBV_SUB_SUB_RTL;

end architecture MyHDL;
