// File: fixbv_top.v
// Generated by MyHDL 0.9.dev0
// Date: Wed May  6 09:55:06 2015


`timescale 1ns/10ps

module fixbv_top (
    clk,
    do_add,
    x_sig,
    y_sig,
    sum_sig,
    done_add,
    do_mul,
    prod_sig,
    done_mul,
    do_sub,
    sub_sig,
    done_sub
);


input clk;
input do_add;
input signed [30:0] x_sig;
input signed [30:0] y_sig;
output signed [31:0] sum_sig;
reg signed [31:0] sum_sig;
output done_add;
reg done_add;
input do_mul;
output signed [62:0] prod_sig;
reg signed [62:0] prod_sig;
output done_mul;
reg done_mul;
input do_sub;
output signed [31:0] sub_sig;
reg signed [31:0] sub_sig;
output done_sub;
reg done_sub;






always @(posedge clk) begin: FIXBV_TOP_DUT_FIXBV_ADD_ADD_RTL
    if ((do_add == 1)) begin
        done_add <= 0;
        sum_sig <= (x_sig + y_sig);
    end
    else begin
        done_add <= 1;
        sum_sig <= 0;
    end
end


always @(posedge clk) begin: FIXBV_TOP_DUT_FIXBV_SUB_SUB_RTL
    if ((do_sub == 1)) begin
        done_sub <= 0;
        sub_sig <= (x_sig - y_sig);
    end
    else begin
        done_sub <= 1;
        sub_sig <= 0;
    end
end


always @(posedge clk) begin: FIXBV_TOP_DUT_FIXBV_MUL_ADD_RTL
    if ((do_mul == 1)) begin
        done_mul <= 0;
        prod_sig <= (x_sig * y_sig);
    end
    else begin
        done_mul <= 1;
        prod_sig <= 0;
    end
end

endmodule
