// File: fixbv_mul.v
// Generated by MyHDL 0.9.dev0
// Date: Mon May  4 13:19:56 2015


`timescale 1ns/10ps

module fixbv_mul (
    clk,
    do_prod,
    x_sig,
    y_sig,
    prod_sig
);


input clk;
input do_prod;
input [31:0] x_sig;
input [31:0] y_sig;
output [63:0] prod_sig;
reg [63:0] prod_sig;






always @(posedge clk) begin: FIXBV_MUL_ADD_RTL
    if ((do_prod == 1)) begin
        prod_sig <= (x_sig * y_sig);
    end
    else begin
        prod_sig <= 0;
    end
end

endmodule
