-- File: fixbv_add.vhd
-- Generated by MyHDL 0.9.dev0
-- Date: Mon May  4 13:19:56 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity fixbv_add is
    port (
        clk: in std_logic;
        do_add: in std_logic;
        x_sig: in unsigned(31 downto 0);
        y_sig: in unsigned(31 downto 0);
        sum_sig: out unsigned(31 downto 0)
    );
end entity fixbv_add;


architecture MyHDL of fixbv_add is






begin




FIXBV_ADD_ADD_RTL: process (clk) is
begin
    if rising_edge(clk) then
        if (do_add = '1') then
            sum_sig <= (x_sig + y_sig);
        else
            sum_sig <= to_unsigned(0, 32);
        end if;
    end if;
end process FIXBV_ADD_ADD_RTL;

end architecture MyHDL;
