// File: fixbv_add.v
// Generated by MyHDL 0.9.dev0
// Date: Mon May  4 13:19:56 2015


`timescale 1ns/10ps

module fixbv_add (
    clk,
    do_add,
    x_sig,
    y_sig,
    sum_sig
);


input clk;
input do_add;
input [31:0] x_sig;
input [31:0] y_sig;
output [31:0] sum_sig;
reg [31:0] sum_sig;






always @(posedge clk) begin: FIXBV_ADD_ADD_RTL
    if ((do_add == 1)) begin
        sum_sig <= (x_sig + y_sig);
    end
    else begin
        sum_sig <= 0;
    end
end

endmodule
