-- File: fixbv_mul.vhd
-- Generated by MyHDL 0.9.dev0
-- Date: Tue May  5 16:25:40 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity fixbv_mul is
    port (
        clk: in std_logic;
        do_mul: in std_logic;
        x_sig: in signed (30 downto 0);
        y_sig: in signed (30 downto 0);
        prod_sig: out unsigned(61 downto 0);
        done_mul: out std_logic
    );
end entity fixbv_mul;


architecture MyHDL of fixbv_mul is






begin




FIXBV_MUL_ADD_RTL: process (clk) is
begin
    if rising_edge(clk) then
        if (do_mul = '1') then
            done_mul <= '0';
            prod_sig <= unsigned(x_sig * y_sig);
        else
            done_mul <= '1';
            prod_sig <= to_unsigned(0, 62);
        end if;
    end if;
end process FIXBV_MUL_ADD_RTL;

end architecture MyHDL;
