// File: jpeg.v
// Generated by MyHDL 0.9dev
// Date: Mon Aug 11 10:34:39 2014


`timescale 1ns/10ps

module jpeg (
    clk_i,
    left_i,
    right_i,
    sam_i,
    updated_i,
    even_odd_i,
    fwd_inv_i,
    noupdate_o,
    res_o
);


input clk_i;
input signed [17:0] left_i;
input signed [17:0] right_i;
input signed [17:0] sam_i;
input updated_i;
input even_odd_i;
input fwd_inv_i;
output noupdate_o;
reg noupdate_o;
output signed [17:0] res_o;
reg signed [17:0] res_o;






always @(posedge clk_i) begin: JPEG_HDL
    if ((updated_i == 1)) begin
        if (even_odd_i) begin
            if (fwd_inv_i) begin
                res_o <= (sam_i - ($signed(left_i >>> 1) + $signed(right_i >>> 1)));
            end
            else begin
                res_o <= (sam_i + ($signed(left_i >>> 1) + $signed(right_i >>> 1)));
            end
        end
        else begin
            if (fwd_inv_i) begin
                res_o <= $signed((sam_i + ((left_i + right_i) + 2)) >>> 2);
            end
            else begin
                res_o <= $signed((sam_i - ((left_i + right_i) + 2)) >>> 2);
            end
        end
    end
    else begin
        noupdate_o <= 1;
    end
end

endmodule
