-- File: mult_mul_add.vhd
-- Generated by MyHDL 0.9dev
-- Date: Mon Jul  7 14:34:28 2014


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_09.all;

entity mult_mul_add is
    port (
        clk: in std_logic;
        pix_addr_r: in unsigned(6 downto 0);
        pix_din_r: in signed (25 downto 0);
        pix_dout_r: in signed (25 downto 0);
        pix_we_r: in std_logic;
        pix_addr_odd: in unsigned(6 downto 0);
        pix_we_odd: in std_logic;
        pix_we_l: in std_logic;
        pix_dout_l: inout signed (25 downto 0);
        pix_dout_odd: out signed (25 downto 0);
        pix_din_odd: inout signed (25 downto 0);
        pix_din_l: in signed (25 downto 0);
        pix_addr_l: in unsigned(6 downto 0)
    );
end entity mult_mul_add;


architecture MyHDL of mult_mul_add is






begin




MULT_MUL_ADD_HDL: process (clk) is
    variable ca1: signed(25 downto 0);
begin
    if rising_edge(clk) then
        pix_din_odd <= resize((pix_dout_l + pix_dout_r) * ca1, 26);
    end if;
end process MULT_MUL_ADD_HDL;

end architecture MyHDL;
