// File: mult_mul_add.v
// Generated by MyHDL 0.9dev
// Date: Mon Jul  7 10:30:04 2014


`timescale 1ns/10ps

module mult_mul_add (
    clk,
    pix_addr_r,
    pix_din_r,
    pix_dout_r,
    pix_we_r,
    pix_addr_odd,
    pix_we_odd,
    pix_we_l,
    pix_dout_l,
    pix_dout_odd,
    pix_din_odd,
    pix_din_l,
    pix_addr_l
);


input clk;
input [6:0] pix_addr_r;
input signed [25:0] pix_din_r;
input signed [25:0] pix_dout_r;
input pix_we_r;
input [6:0] pix_addr_odd;
input pix_we_odd;
input pix_we_l;
input signed [25:0] pix_dout_l;
output signed [25:0] pix_dout_odd;
reg signed [25:0] pix_dout_odd;
input signed [25:0] pix_din_odd;
input signed [25:0] pix_din_l;
input [6:0] pix_addr_l;






always @(posedge clk) begin: MULT_MUL_ADD_HDL
    reg signed [26-1:0] ca1;
    pix_dout_odd <= ((pix_dout_l + pix_dout_r) * ca1);
end

endmodule
