// File: ram_even.v
// Generated by MyHDL 0.9dev
// Date: Sat Jul 12 11:34:28 2014


`timescale 1ns/10ps

module ram_even (
    clk,
    pix_right,
    pix_we_even,
    pix_p,
    pix_addr_odd,
    pix_fwd_inv,
    pix_addr_even,
    pix_din_even,
    pix_we_odd,
    pix_dout_odd,
    pix_din_odd,
    pix_dout_even,
    pix_even_odd,
    pix_left
);
// Ram model 

input clk;
input [9:0] pix_right;
input pix_we_even;
input pix_p;
input [6:0] pix_addr_odd;
input pix_fwd_inv;
input [6:0] pix_addr_even;
input signed [8:0] pix_din_even;
input pix_we_odd;
output signed [8:0] pix_dout_odd;
wire signed [8:0] pix_dout_odd;
input signed [8:0] pix_din_odd;
output signed [8:0] pix_dout_even;
wire signed [8:0] pix_dout_even;
input pix_even_odd;
input [9:0] pix_left;


reg signed [8:0] mem_even [0:128-1];




always @(posedge clk) begin: RAM_EVEN_WRITE_EVEN
    if (pix_we_even) begin
        mem_even[pix_addr_even] <= pix_din_even;
    end
end



assign pix_dout_even = mem_even[pix_addr_even];

endmodule
