-- File: pc_read.vhd
-- Generated by MyHDL 0.9.dev0
-- Date: Mon May 18 12:47:16 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity pc_read is
    port (
        clk: in std_logic;
        data_in: out unsigned(8 downto 0);
        toLift_Step: in unsigned(8 downto 0);
        we_in: out std_logic;
        addr_in: inout unsigned(7 downto 0);
        muxsel_i: inout std_logic;
        datactn_in: out unsigned(7 downto 0);
        datactn: in unsigned(7 downto 0);
        pc_data_in: inout unsigned(1 downto 0);
        pc_data_rdy: in unsigned(1 downto 0)
    );
end entity pc_read;


architecture MyHDL of pc_read is






begin




PC_READ_READLOGIC: process (clk) is
begin
    if rising_edge(clk) then
        if (muxsel_i = '1') then
            if (addr_in <= 254) then
                we_in <= '1';
                data_in <= toLift_Step;
                datactn_in <= datactn;
                addr_in <= (addr_in + 1);
            end if;
        end if;
    end if;
end process PC_READ_READLOGIC;



pc_data_in <= pc_data_rdy;


PC_READ_RTL1: process (clk) is
begin
    if rising_edge(clk) then
        if (muxsel_i = '0') then
            if (pc_data_in = 3) then
                muxsel_i <= '1';
            else
                if (pc_data_in = 2) then
                    muxsel_i <= '0';
                end if;
            end if;
        end if;
    end if;
end process PC_READ_RTL1;

end architecture MyHDL;
