-- File: pc_read.vhd
-- Generated by MyHDL 0.9.dev0
-- Date: Fri May 22 18:47:39 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity pc_read is
    port (
        clk: in std_logic;
        data_in: out unsigned(8 downto 0);
        toLift_Step: in unsigned(8 downto 0);
        addr_in: out unsigned(7 downto 0);
        addr_in_toLift_Step: in unsigned(7 downto 0);
        read_pc_i: in std_logic;
        muxsel_i: in std_logic;
        pc_data_in: out unsigned(1 downto 0);
        pc_data_rdy: in unsigned(1 downto 0);
        we_in: out std_logic
    );
end entity pc_read;


architecture MyHDL of pc_read is






begin




PC_READ_RTL: process (toLift_Step, addr_in_toLift_Step, pc_data_rdy, read_pc_i, muxsel_i) is
begin
    if ((read_pc_i = '1') and (muxsel_i = '1')) then
        pc_data_in <= pc_data_rdy;
        data_in <= toLift_Step;
        addr_in <= addr_in_toLift_Step;
        we_in <= '1';
    else
        pc_data_in <= to_unsigned(0, 2);
        data_in <= to_unsigned(0, 9);
        addr_in <= to_unsigned(0, 8);
        we_in <= '0';
    end if;
end process PC_READ_RTL;

end architecture MyHDL;
